
create table players_fantasy_stat
(
    `index` bigint null,
    id bigint not null,
    club_id bigint not null,
    tag_id bigint null,
    now_id bigint not null,
    team_id bigint null,
    club text null,
    amplua text null,
    price text null,
    is_disqual bigint null,
    is_injured bigint null,
    is_star bigint null,
    row text null,
    `order` text null,
    isCaptain text null,
    name text null,
    season text null,
    tour bigint not null,
    img text null,
    tour_score double null,
    tour_name text null,
    min text null,
    goals text null,
    pass text null,
    thru text null,
    ycard text null,
    rcard text null,
    created timestamp default CURRENT_TIMESTAMP not null,
    updated timestamp default CURRENT_TIMESTAMP not null,
    points bigint null,
    primary key (id, club_id, now_id, tour)
);